export const Config = {
  LISTEN_PORT: parseInt(process.env.CERC_NITRO_AUTH_LISTEN_PORT || '8547'),
  LISTEN_ADDR: process.env.CERC_NITRO_AUTH_LISTEN_ADDR || '0.0.0.0',
  GETH_HTTP_URL: process.env.CERC_NITRO_GETH_HTTP_URL || 'http://localhost:8545',
  GETH_FREE_METHODS: (process.env.CERC_NITRO_GETH_FREE_METHODS || 'eth_chainId,eth_blockNumber,net_version').split(',').map(x => x.trim()),
  NITRO_RPC_HOST: process.env.CERC_NITRO_AUTH_RPC_HOST || '127.0.0.1',
  NITRO_RPC_PORT: process.env.CERC_NITRO_AUTH_RPC_PORT || '4007',
  NITRO_RPC_SECURE: 'true' === (process.env.CERC_NITRO_RPC_SECURE || 'false'),
  NITRO_PK: process.env.CERC_NITRO_PK,
  NITRO_WS_MSG_PUBLIC_IP: process.env.CERC_NITRO_MSG_PUBLIC_IP || '127.0.0.1',
  NITRO_WS_MSG_PUBLIC_PORT: process.env.CERC_NITRO_MSG_PUBLIC_PORT || '5005',
  NITRO_CONTRACT_CA_ADDRESS: process.env.CERC_CA_ADDRESS,
  NITRO_CONTRACT_NA_ADDRESS: process.env.CERC_NA_ADDRESS,
  NITRO_CONTRACT_VPA_ADDRESS: process.env.CERC_VPA_ADDRESS,
  HTTP_SERVER_KEEPALIVE_TIMEOUT: parseInt(process.env.CERC_NITRO_HTTP_SERVER_KEEPALIVE_TIMEOUT || '60000'),
  HTTP_SERVER_TIMEOUT: parseInt(process.env.CERC_NITRO_HTTP_SERVER_TIMEOUT || '30000'),
  HTTP_SERVER_BACKLOG: parseInt(process.env.CERC_NITRO_HTTP_SERVER_BACKLOG || '10000'),
  FASTIFY_LOGGER: 'true' === (process.env.CERC_NITRO_FASTIFY_LOGGER || 'true'),
};
